openapi: 3.1.0
info:
  title: Voice Payments API
  version: 0.1.0
servers:
  - url: http://localhost:4000
paths:
  /api/voice-to-text:
    post:
      summary: Upload audio and receive transcript
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audio:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  transcript:
                    type: string
  /api/interpret:
    post:
      summary: NLP interpret transcript
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transcript:
                  type: string
      responses:
        '200':
          description: Intent JSON 